version: "3"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: reviewers
      POSTGRES_USER: reviewers
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

