[package]
name = "reviewers-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive", "env"] }
color-eyre = "0.6.3"
dotenvy = "0.15.7"
eyre = "0.6.12"
rocket = "0.5.1"
sqlx = "0.8.3"
