[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true }
rxing = "0.7.1"
ui = { workspace = true }

[features]
default = []
web = ["dioxus/web", "dioxus/file_engine"]
server = ["dioxus/server"]
